services:
  - type: web
    name: sahaja-krushi-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

